### ISSUE TITLE
Dependency errors

### ISSUE THREAD

**Issue by kmurphypolygon** [orzih/mkdocs-with-pdf#157]
Hello, I'm getting these errors on running the plugin, and only 5 pages are published out of 437

```
INFO    -  DeprecationWarning: transform is deprecated, use set_matrix instead.
             File "/Users/kmurphy/Library/Python/3.12/lib/python/site-packages/weasyprint/pdf/stream.py", line 246, in
           transform
               super().transform(a, b, c, d, e, f)
             File "/Users/kmurphy/Library/Python/3.12/lib/python/site-packages/pydyf/__init__.py", line 404, in
           transform
               warn(Stream.transform.__doc__, DeprecationWarning)
INFO    -  DeprecationWarning: text_matrix is deprecated, use set_text_matrix instead.
             File "/Users/kmurphy/Library/Python/3.12/lib/python/site-packages/weasyprint/draw.py", line 1356, in
           draw_first_line
               stream.text_matrix(*matrix.values)
             File "/Users/kmurphy/Library/Python/3.12/lib/python/site-packages/pydyf/__init__.py", line 399, in
           text_matrix
               warn(Stream.text_matrix.__doc__, DeprecationWarning)
INFO    -  DeprecationWarning: shading is deprecated, use paint_shading instead.
             File "/Users/kmurphy/Library/Python/3.12/lib/python/site-packages/weasyprint/svg/defs.py", line 230, in
           draw_gradient
               group.shading(shading.id)
             File "/Users/kmurphy/Library/Python/3.12/lib/python/site-packages/pydyf/__init__.py", line 248, in shading
               warn(Stream.shading.__doc__, DeprecationWarning)
INFO    -  DeprecationWarning: color_space is deprecated, use set_color_space instead.
             File "/Users/kmurphy/Library/Python/3.12/lib/python/site-packages/weasyprint/svg/defs.py", line 233, in
           draw_gradient
               svg.stream.color_space('Pattern', stroke=stroke)
             File "/Users/kmurphy/Library/Python/3.12/lib/python/site-packages/pydyf/__init__.py", line 126, in
           color_space
               warn(Stream.color_space.__doc__, DeprecationWarning)
```

Any help most welcome.

**Comment by Thiti517** [comment]
Hello!

I encountered the same issue, and after investigating the code for *mkdocs-with-pdf*, I discovered that the problem stems from a dependency of [WeasyPrint](https://github.com/Kozea/WeasyPrint/tree/main) called [pydyf](https://github.com/CourtBouillon/pydyf) in version `0.11.0`. According to the [release notes](https://github.com/CourtBouillon/pydyf/releases/tag/v0.11.0), the update includes:

> *Changed some function names for consistency.*

These changes affect the functions used by *WeasyPrint*, causing deprecation warnings that are subsequently reported by *mkdocs-with-pdf*.

Since *WeasyPrint* requires a version of *pydyf* equal to or greater than `0.10.0`, it will automatically install the latest version `0.11.0`, as it satisfies *WeasyPrint*'s requirements.

From what I observed in the *WeasyPrint* repository, the function names in *pydyf* have already been updated. Therefore, future versions (`>62.3`) of *WeasyPrint* should address this deprecation issue.

In the meantime, to avoid these warnings, ensure you have version `0.10.0` of *pydyf* installed.

```
> pip install pydyf==0.10.0
```

The result of the command:
```
Collecting pydyf==0.10.0
Installing collected packages: pydyf
  Attempting uninstall: pydyf
    Found existing installation: pydyf 0.11.0
    Uninstalling pydyf-0.11.0:
      Successfully uninstalled pydyf-0.11.0
Successfully installed pydyf-0.10.0
```

**Comment by kmurphypolygon** [comment]
Amazing, thank you, will check this out :D

**Comment by kmurphypolygon** [comment]
Fixed, thank you :)

**Comment by Thiti517** [comment]
Aaah glad to hear it worked !
